### ISSUE TITLE
formCode в параметре

### ISSUE THREAD

**Issue by luza** [makcemycsh/cloud#5]
Нужно, чтобы урл формы выглядел так:
https://form.cloudloyalty.ru/kofelavka

В зависимости от пути, должна рендериться форма под разные бренды.
В бекенде я сделал так, чтобы на любой урл возвращалось содержимое index.html, теперь нужно добавить поддержку этого во VueRouter.

**Comment by makcemycsh** [comment]
https://github.com/makcemycsh/cloud/commit/998676e6195903ee685891dca892ff81dc856e37
