### ISSUE TITLE
Форма требует заполнения необязательных полей

### ISSUE THREAD

**Issue by luza** [makcemycsh/cloud#6]
Дети - необязательное поле, но форма требует их заполнения
То же с полем email
![image](https://user-images.githubusercontent.com/1804178/73664372-54da4300-46b0-11ea-8557-454e9b5a6c34.png)

**Comment by makcemycsh** [comment]
https://github.com/makcemycsh/cloud/commit/aa94ac0087e0aa55e5b8252d7a538c631bf583aa
